name: 'Suggester Build'
on:
  push:
    branches: [ 'ver/latest ']
  pull_request:
    branches: [ 'ver/latest' ]
jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v3'
      - name: 'Install Java Development Kit (17)'
        uses: 'actions/setup-java@v3'
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: 'Build (Maven)'
        run: 'mvn clean package'
      - name: 'Upload Artifact'
        uses: 'actions/upload-artifact@v3'
        with:
          name: 'Built Artifact'
          path: 'target/*.jar'
